
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files (excluding metadata and analysis)
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-metadata: ## Remove generated metadata files (preserves original AudioSet files)
	@echo "Removing generated metadata files..."
	find meta/ -mindepth 2 -name "*.tsv" -type f -delete 2>/dev/null || true
	find meta/ -mindepth 2 -name "*.csv" -type f -delete 2>/dev/null || true
	find meta/ -type d -empty -delete 2>/dev/null || true
	@echo "Generated metadata files removed (original AudioSet files preserved)"

clean-analysis: ## Remove all analysis output files
	@echo "Removing all analysis output files..."
	rm -rf out/
	@echo "Analysis files removed"

clean-all: clean clean-metadata clean-analysis ## Clean everything (autogenerated files, metadata, and analysis)
	@echo "All generated files cleaned"

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main
