pos_strong_paths: ["./meta/baby_cry/seg1s/pos/baby_cry_ov_audioset_train_strong.tsv",
                  "./meta/baby_cry/seg1s/pos/baby_cry_ov_audioset_eval_strong.tsv",
                  "./meta/baby_cry/seg1s/pos/baby_cry_nov_audioset_train_strong.tsv",
                  "./meta/baby_cry/seg1s/pos/baby_cry_nov_audioset_eval_strong.tsv"]

neg_strong_paths: ["./meta/baby_cry/seg1s/neg_strong/baby_cry_audioset_train_strong.tsv",
                  "./meta/baby_cry/seg1s/neg_strong/baby_cry_audioset_eval_strong.tsv"]

neg_weak_paths: ["./meta/baby_cry/raw/neg_weak/baby_cry_neg_weak_unbalanced_train_segments.csv",
                "./meta/baby_cry/raw/neg_weak/baby_cry_neg_weak_balanced_train_segments.csv",
                "./meta/baby_cry/raw/neg_weak/baby_cry_neg_weak_eval_segments.csv"]

